### ISSUE TITLE
Test old state support

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#108]
Some RPC methods like `starknet_call` offer the user to perform a call at a historic block, by providing an old block specifier (by hash or number). Candidate methods include those that read the state and have `block_id` as their argument in the [RPC spec file](https://github.com/0xSpaceShard/starknet-devnet-rs/blob/main/crates/starknet-devnet-server/test_data/spec/0.7.1/starknet_api_openrpc.json): `starknet_call`, `starknet_estimateFee`, `starknet_estimateMessageFee`, `starknet_getStorageAt`, `starknet_getNonce`, `starknet_getClass`, `starknet_simulateTransactions`.

The old state support itself was introduced with #104, but not thoroughly tested. Currently we only test with `BlockId::Tag(BlockTag::Latest)`, but it would make sense to also test with `BlockId::Number(<HISTORIC_BLOCK_NUMBER>)` and `BlockId::Hash(<HISTORIC_BLOCK_HASH>)`

**Comment by vibenedict** [comment]
@FabijanC please can you add more description and what to do for this issue? It will be my please to tackle it

**Comment by FabijanC** [comment]
@vibenedict description updated

**Comment by vibenedict** [comment]
Hi @FabijanC, looking at the linked PR, I can't seems to find the file where `BlockId::Tag(BlockTag::Latest)` was tested. It would make my work faster if you could add link to the file in the description. Thanks

**Comment by FabijanC** [comment]
E.g. `starknet_call` is tested in https://github.com/0xSpaceShard/starknet-devnet-rs/blob/ed53233079c9dc338ea432d18e2eeb4e43ab85b2/crates/starknet-devnet/tests/test_call.rs#L28. Would be cool to test the case where there are e.g. 3 blocks, and you want to call with block_id being number 2. Also testing by hash would be good. Just be sure to spawn the background devnet with `--state-archive-capacity full` (see other instances of it).
