### ISSUE TITLE
Trait Accounted treating balance in a wrong way

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#110]
The balance is stored in two memory places (two consecutive storage addresses) whereas we only deal with one (both in `set_initial_balance` and `get_balance`). This lowers the upper bound on the values we can store. E.g. in Pythonic Devnet the chargeable account was using an initial balance of 2^251 so I wanted to set it here as well, but 2^128 is the maximum. We can probably live with 2^128 for the chargeable account, but we will have problems if a user specifies account initial balance to be greater than that.

In Pythonic Devnet, the balance is set like this:
https://github.com/0xSpaceShard/starknet-devnet/blob/7840c9dc1735d9bebb9d7bd0264714a502587c0b/starknet_devnet/account_util.py#L119-L140

**Comment by ivpavici** [comment]
@FabijanC to double check!

**Comment by FabijanC** [comment]
I confirm, this is still a problem. Steps to reproduce:
1. In one terminal start Devnet with:
```
cargo run --release -- --accounts 1 --initial-balance 340282366920938463463374607431768211456 --seed 3798524267
```

2. After Devnet has started, in a different terminal send:
```bash
curl localhost:5050/mint \
    --json "{ \"address\": \"0x5892937864ed57e12f4542b996319502dd0986f1a50b6a07c2ed2fed1364375\", \"amount\": 1 }"
```

3. Receive error:
```
{"error":"Minting error: Execution failed. Failure reason: 0x53746f726555313238202d206e6f6e2075313238 ('StoreU128 - non u128')."}
```

**Comment by JimmyFate** [comment]
Hello, I've ran into this issue myself recently, so I'd be down to kill 2 birds with one stone and open a PR referencing this.
Have you thought of any solution to this maybe? Adding a `U256` type and replacing `u128` with it would probably do the job - wdyt?

**Comment by ivpavici** [comment]
@JimmyFate feel free t propose a PR and we can discuss further!
