### ISSUE TITLE
Post-deploy steps separate from deploy in Account

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#111]
Currently we need to deploy an account and set its balance as separate steps. Ideally this would be done with a single call (and potential other post-deploy steps).

**Comment by SamSamV** [comment]
hi can i take this issue ?

**Comment by FabijanC** [comment]
Hi @SamSamV, I'll assign you.

**Comment by ivpavici** [comment]
@SamSamV hi! any news on this? :D

**Comment by muheebyusufbaba1** [comment]
Can I work on this issue?

**Comment by muheebyusufbaba1** [comment]
I would like to work on this

**Comment by muheebyusufbaba1** [comment]
Hi @FabijanC, please can you link me up with the files where the deployment functions need to be added? This would speed up my work on this issue as the codebase it pretty large and it may take some time to get familiar with it

**Comment by muheebyusufbaba1** [comment]
And maybe add more description to the issue :) 
Thanks

**Comment by FabijanC** [comment]
Turns out this issue was resolved by #329. Sorry if you lost your time. Your comments were actually helpful because they helped us realize that this issue can be closed. Hopefully you've acquainted yourself with the codebase. Cheers

**Comment by muheebyusufbaba1** [comment]
I have already burnt through a couple of hours though :)
I would be glad if maybe you could assign another issue to me since this one is resolved already.
@FabijanC

**Comment by FabijanC** [comment]
If you're interested in https://github.com/0xSpaceShard/starknet-devnet-rs/issues/258, feel free to leave a comment there so I can assign you

**Comment by ivpavici** [comment]
@muheebyusufbaba1 I've sent you a small reward in OnlyDust
