### ISSUE TITLE
Update RPC to v0.4.0

### ISSUE THREAD

**Issue by ivpavici** [0xSpaceShard/starknet-devnet-rs#132]
Release:
https://github.com/starkware-libs/starknet-specs/releases/tag/v0.4.0

- [ ] The reverted transaction status has been introduced, and receipts have the optional revert_reason property https://github.com/starkware-libs/starknet-specs/pull/99 https://github.com/starkware-libs/starknet-specs/pull/106
- [ ] Trace API: code hash is renamed to class hash & simulateTransaction is renamed to simulateTransactions https://github.com/starkware-libs/starknet-specs/pull/104
- [ ] Split status into execution_status and finality_status https://github.com/starkware-libs/starknet-specs/pull/107
- [ ] Invoke v0 transaction: remove nonce and rename sender_address to contract_address https://github.com/starkware-libs/starknet-specs/pull/108
- [ ] Simulation flags: removed SKIP_EXECUTE and added SKIP_FEE_CHARGE https://github.com/starkware-libs/starknet-specs/pull/109
- [ ] Added the starknet_estimateMessageFee endpoint https://github.com/starkware-libs/starknet-specs/pull/100 https://github.com/starkware-libs/starknet-specs/pull/115
- [ ] Refactored errors: many unused error codes were removed, and error codes that correspond to potential gateway replies were added to the write API https://github.com/starkware-libs/starknet-specs/pull/113 https://github.com/starkware-libs/starknet-specs/pull/119
- [ ] Flattened the transaction structures to make the spec more readable https://github.com/starkware-libs/starknet-specs/pull/114
- [ ] Added Cairo v>=2.0.0 ABI specs https://github.com/starkware-libs/starknet-specs/pull/117
- [x] Reintroduced DECLARE_TXN_V0 since it may still be returned in historical blocks https://github.com/starkware-libs/starknet-specs/pull/120

**Comment by marioiordanov** [comment]
In devnet-rs there is no InvokeV0 transactions implemented
