### ISSUE TITLE
DeclareTransaction to types

### ISSUE THREAD

**Issue by taco-paco** [0xSpaceShard/starknet-devnet-rs#140]
Right now `model` crate's `BroadcastedDeclareTransaction` is converted to `starknet` crate's `DeclareTransaction` and then on request `get_transaction_by_something` `starknet`'s DeclareTransaction gets converted to models `DeclareTransaction`.

TODO: Move model's transaction types to  `types/rpc`. remove `starknet`'s `DeclareTransaction` and replace with types/rpc DeclareTransaction

**Comment by marioiordanov** [comment]
fixed long time ago
