### ISSUE TITLE
Incorrect getClass response and error code

### ISSUE THREAD

**Issue by DelevoXDG** [0xSpaceShard/starknet-devnet-rs#145]
**Describe the bug (observed vs expected behavior)**
getClass returns incorrect response when passing `class_hash` of a contract that is not yet declared as a parameter.

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Run starknet-devnet-rs:
```shell
starknet-devnet --host 0.0.0.0 --port 5051
```
2. Make getClass request with `class_hash` of a contract that is not yet declared:
```shell
curl -XPOST -H "Content-Type: application/json" -d '{"id":0, "jsonrpc":"2.0", "method":"starknet_getClass", "params":{"block_id":"pending","class_hash":"0x111111111111111111111111111111111111"}}' "http://0.0.0.0:5051/rpc"
```
Expected response:
```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": 28,
    "message": "Class hash not found"
  },
  "id": 0
}                                                                                               
```
Actual response:
```json
{
  "jsonrpc": "2.0",
  "id": 0,
  "error": {
    "code": -1,
    "message": "No compiled class hash found for class_hash [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17]"
  }
}
```

**Comment by taco-paco** [comment]
Thanks for reporting this! Will verify and fix
