### ISSUE TITLE
Missing contract_address in getTransactionReceipt response 

### ISSUE THREAD

**Issue by DelevoXDG** [0xSpaceShard/starknet-devnet-rs#147]
**Describe the bug (observed vs expected behavior)**
`getTransactionReceipt` returns an incorrect response where `contract_address` field is missing.

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

Assuming tx with hash 0x111111111 exists, run:
```shell
curl -XPOST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"starknet_getTransactionReceipt","params":["0x111111111"],"id":1}' "http://0.0.0.0:5051/rpc"
```

**Comment by marioiordanov** [comment]
@DelevoXDG what is the transaction type that is being executed. The getTransactionReceipt returns contract_address only for deploy transactions

**Comment by DelevoXDG** [comment]
Deploy account

**Comment by marioiordanov** [comment]
Thanks for reporting it, it will be fixed asap
