### ISSUE TITLE
Reverted & rejected txs

### ISSUE THREAD

**Issue by taco-paco** [0xSpaceShard/starknet-devnet-rs#150]
Right now adds rejected txs to transaction list. TODO: implement py devnet's logic with discarding them. Add reverted transactions to block and not leave them in pending state

**Comment by FabijanC** [comment]
Can be used for reference: https://github.com/0xSpaceShard/starknet-devnet/pull/518

**Comment by FabijanC** [comment]
Turns out with the merge of blockifier in #193 the path for this has been largely paved
