### ISSUE TITLE
Using starknet-rs codegen type wrappers

### ISSUE THREAD

**Issue by taco-paco** [0xSpaceShard/starknet-devnet-rs#156]
In `types` crate(once migration is over) we have our own custom types that actually just a copy of `starknet-rs ` [codegenerated types](https://github.com/xJonathanLEI/starknet-rs/blob/master/starknet-core/src/types/codegen.rs). Why don't we use wrappers on those types?

```
struct SomeTypeWrapper {
     inner: SomeType
}
```

 This will have couple of advantages: 
1. once rpc specs are updated there's no need to spend time on manual updating. In new feature branch updating `starknet-rs` with corresponding commit will result in compilation errors which one will just have to fix to support the whole new rpc spec.
2. Type mismatches. I had two scenarios of types not being 1-1 to rpc-spec with ContractClass and receipts. This results in deserialisation error on client side saying: `Other(TransportError(Json(Error("data did not match any variant of untagged enum JsonRpcResponse", line: 0, column: 0))))'`. Looks like keeping custom types results in human error that can be avoided

The question here is: what do you guys think @marioiordanov @FabijanC? What was the reason behind creating custom types? Am I missing something?

**Comment by marioiordanov** [comment]
I agree with that one. About the custom types creation, I wasn't aware back then in the starknet-rs project purpose and what  it offers.

**Comment by taco-paco** [comment]
Ok `estimate_message_fee` will be using this approach. And if everything will look good we will slowly migrate to this approach

**Comment by ivpavici** [comment]
Could be solved in the future when the RPC spec becomes more stable
