### ISSUE TITLE
Malformed class hash in error message

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#164]
A user on Discord has reported ([link to thread](https://discord.com/channels/793094838509764618/1151036560989487184)) an issue with using starknet-devnet-rs, but what caught my eye was the format of the error:
![image](https://github.com/0xSpaceShard/starknet-devnet-rs/assets/28579396/62236e22-8043-4b5f-8526-6021a9af35bf)

This is probably happening because we catch starknet_in_rust errors and just do:
```rust
Err(err) => Err(ApiError::ContractError { msg: err.to_string() }),
```

The user's problem is probably that the class hasn't been declared, so this issue isn't concerned with that.

Perhaps we could do something smarter to display the error (i.e. the class hash) better. Or perhaps this can be fixed on starknet_in_rust side.

**Comment by marioiordanov** [comment]
#193 fixes it
