### ISSUE TITLE
Introduce the dump/load feature

### ISSUE THREAD

**Issue by ivpavici** [0xSpaceShard/starknet-devnet-rs#17]
After the MVP is released, this should be the top priority!

https://0xspaceshard.github.io/starknet-devnet/docs/guide/dumping-and-loading

**Comment by mikiw** [comment]
In the old devnet, we used https://github.com/cloudpipe/cloudpickle for "pickling" objects to Python binary pickle format.
There is a rust library that supports that format (https://docs.rs/serde-pickle/latest/serde_pickle/) but I'm not sure if we need that format support.

I would use [serde ](https://serde.rs/) and binary formatter like [bincode](https://github.com/bincode-org/bincode) or similar to save disc space.

**Comment by mikiw** [comment]
Seems that https://crates.io/crates/bincode/1.3.3 is good choice https://github.com/djkoloski/rust_serialization_benchmark
