### ISSUE TITLE
localhost is not a valid argument for --host flag

### ISSUE THREAD

**Issue by DelevoXDG** [0xSpaceShard/starknet-devnet-rs#170]
**Describe the bug (observed vs expected behavior)**
`localhost` is not a valid argument for `--host` flag

**Not reproducible on alpha-goerli**

- [x] This issue is only present on devnet-rs.
- [x] This issues is not present on pythonic devnet.

**To Reproduce**

1. Run starknet-devnet with `localhost` as desired host:
```bast
starknet-devnet --host localhost --port 5051 --seed 0
```
**Expected behaviour:** 
Devnet starts normally. Unless there's a very good reason to allow only numerical ip addresses.

**Actual behaviour:** 
```
thread 'main' panicked at 'Invalid value for host IP address: AddrParseError(Ip)', crates/starknet-server/src/main.rs:57:57
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
   3: tokio::runtime::park::CachedParkThread::block_on
   4: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
   5: tokio::runtime::runtime::Runtime::block_on
   6: starknet_devnet::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
``` 

**Devnet version**

- I am using Devnet version: 7586b55d221e9010809a6e61b7e28e53fc9ff5c2
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version: `pythonic devnet 0.6.2`

**System specifications**

- OS: macOS aarch64

**Comment by FabijanC** [comment]
I don't think this is a high priority bug as it can probably be worked around by specifying `--host 127.0.0.1`.

In my fix, that I'll do this week, I'll probably:
1. Do the host parsing earlier in the startup, when parsing CLI arguments - to prevent stack trace and panic to be visible
2. Simply check if the input string is `"localhost"` and replace it with `127.0.0.1`. 
    - Apparently this won't work if the user wants IPv6 support (i.e. for `localhost` to resolve to `::1`)
    - The actual host will be printed on startup, as it already is.
