### ISSUE TITLE
Important classes (e.g. accounts) should be predeclared

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#171]
Talking about different account classes (Braavos, Argent, Open Zeppelin). Perhaps even multiple versions of the same account could be declared. Currently we only predeclare one Cairo0 Open Zeppelin class (edit: and Cairo1 OZ after #373). Not sure if there are other (i.e. non-account) classes to be considered.

Either these classes could always be predeclared or the user could somehow specify in the CLI which classes they need. The predeclared classes, together with their hashes, could be logged.

## Forking

In Pythonic Devnet, a workaround for this is to use forking: when you fork, all the classes on the origin are also available in the forked Devnet instance. So perhaps this issue could be closed if forking is implemented.

### Pros
- Users don't need to deal with account artifacts

### Cons
- The classes need to be maintained

**Comment by ivpavici** [comment]
related #195
