### ISSUE TITLE
L1-L2 postman functionality should be introduced

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#173]
As was in devnet-py: https://0xspaceshard.github.io/starknet-devnet/docs/guide/postman

In devnet-py, we depended on a modified version of the Postman subsystem of the cairo-lang Python package, my guess is that something similar will have to exist in our Starknet runtime (starknet_in_rust), and I feel it doesn't.

**Comment by FabijanC** [comment]
I just remembered, in devnet-py, we didn't directly rely on cairo-lang's Postman module. We had copied their code, and modified it to suit our needs. It's all in the [postman_wrapper.py](https://github.com/0xSpaceShard/starknet-devnet/blob/master/starknet_devnet/postman_wrapper.py) file

cc: @mikiw

**Comment by glihm** [comment]
Would be happy to work on this. 🙏🏻
