### ISSUE TITLE
Invoking contract causes `actualFee` to be equal to `maxFee`

### ISSUE THREAD

**Issue by DelevoXDG** [0xSpaceShard/starknet-devnet-rs#180]
**Describe the bug (observed vs expected behavior)**

Executing an invoke transaction with a specific `maxFee` causes `actualFee` to be equal to `maxFee`, even though it is obvious `actualFee` should be smaller than excessively large `maxFee`.

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).
- [x] This issue is not present in pythonic devnet.

**To Reproduce**

In [starknet-jvm](https://github.com/software-mansion/starknet-jvm):
```kotlin
        val call = Call(
            contractAddress = balanceContractAddress,
            calldata = listOf(Felt(10)),
            entrypoint = "increase_balance",
        )

        val maxFee = Felt(10000000000000000L)
        val result = account.execute(call, maxFee).send()
        val receipt = provider.getTransactionReceipt(result.transactionHash).send()

        assertTrue(receipt.actualFee!! < maxFee) // fails
```
The respective requests are:
1. Sending invoke transaction
```json
{"jsonrpc":"2.0","method":"starknet_addInvokeTransaction","id":0,"params":{"invoke_transaction":{"sender_address":"0x43924189225e4e5d6c13a7b69417a259f54271679ce8befcdea665c6344231d","calldata":["0x1","0x7dc474450f2e8df002debfd410ed7dea43bfbca62349538e9f181e93024a5a6","0x362398bec32bc0ebb411203221a35a0301193a96f317ebe5e40be9f60d15320","0x0","0x1","0x1","0xa"],"signature":["0x375fc5c12ef189bd9be9c01df00184eca69a85296ce751bc1f8bec0119cebf1","0x44455e06118b0686de7c53684f3c32ae9abdaa76deb668cab840d2f670d6a7a"],"max_fee":"0x2386f26fc10000","version":"0x1","nonce":"0x3","type":"INVOKE"}}}
```
2. Getting the receipt
```json
{"jsonrpc":"2.0","method":"starknet_getTransactionReceipt","id":0,"params":{"transaction_hash":"0x6fd3d130180da8c84ea8c3821f3cb851075ecfece7afef798c7021afea5ace7"}}
```
Response:
```json
{"jsonrpc":"2.0","id":0,"result":{"type":"INVOKE","transaction_hash":"0x6fd3d130180da8c84ea8c3821f3cb851075ecfece7afef798c7021afea5ace7","actual_fee":"0x2386f26fc10000","messages_sent":[],"events":[{"from_address":"0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7","keys":["0x99cd8bde557814842a3121e8ddfd433a539b8c9f14bf31ebf108d12e6196e9"],"data":["0x43924189225e4e5d6c13a7b69417a259f54271679ce8befcdea665c6344231d","0x1000","0x1c1a778608000","0x0"]}],"execution_status":"SUCCEEDED","finality_status":"ACCEPTED_ON_L2","block_hash":"0x10ad59de640ae1cd3dc0a095ea95c93c22c8467700fd913d6b737bd2cb27aa6","block_number":9}}
```
where `actual_fee` == `max_fee` from invoke transaction.

**Expected behaviour:**
`assertTrue(receipt.actualFee!! < maxFee)` succeeds
**Actual behaviour:**
`assertTrue(receipt.actualFee!! < maxFee)` fails

**Devnet version**

- I am using Devnet version: 8c4b73361cb1e15412c68f18ef18da08586a8461
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version: pythonic devnet 0.6.2

**System specifications**

- OS: macOS aarch64

**Comment by marioiordanov** [comment]
#193 partially fix this issue. Now there is an error stating that max fee is not enough to cover actual fee

**Comment by FabijanC** [comment]
Found the responsible line + another bug just below it (messages sent shouldn't be empty):
https://github.com/0xSpaceShard/starknet-devnet-rs/blob/72c11f63aa01a6b02a55d09cdcd3cdfe5c58a1cc/crates/types/src/rpc/transactions.rs#L122-L123
