### ISSUE TITLE
Cairo 1 predeployed account contract

### ISSUE THREAD

**Issue by DelevoXDG** [0xSpaceShard/starknet-devnet-rs#187]
## Feature request
I don't know if this is relevant to #183 or #144, but would it be possible to have both Cairo 0 and Cairo 1 OZ account contracts as predeployed contracts on devnet? 

One of the main use cases of `--account-class` would be to test using **any** cairo 1 account, so maybe we could have a solution that does not necessarily requires to provide path to and maintain said contract.

This cairo 1 account contract could be built in alongside cairo 0 (which, truth be told, would double the number of predeployed accounts and make logs a bit more confusing). 
So alternatively, there could be an ability to toggle between implementation version using some other flag.

**Comment by FabijanC** [comment]
`--account-class` could work with both path and specifier string. E.g.:

1. check if the provided input is a predefined string value (e.g. `oz-0.5.1`, `oz-0.7.0-rc0`, ...)
2. if not, check if it's a valid path
3. if not, error

**Comment by DelevoXDG** [comment]
Good idea, I would separate that to something like `--account-class-path` and `--account-class`, but either way is fine.
