### ISSUE TITLE
Contract deployment accepted if invalid number of constructor arguments

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#190]
Originally reported by Software Mansion. I checked by running the test case `deploy_transaction_receipt` defined in `crates/starknet-server/tests/get_transaction_receipt_by_hash.rs`. I replaced the empty `vec![]` passed to `contract_factory.deploy(...)` with `vec![FieldElement::ZERO]`, printed the received receipt and it said the status is succeeded.

I tried investigating a bit to see where and how deployment is done, but none of those places seem to handle constructor arguments, and even starknet_in_rust's state.deploy_contract only accepts address and class_hash.

**Comment by marioiordanov** [comment]
fixed via #193, but add tests to ensure correct behaviour
