### ISSUE TITLE
Dump and load improvements

### ISSUE THREAD

**Issue by mikiw** [0xSpaceShard/starknet-devnet-rs#197]
- Check the possibility of async functions in \starknet\src\starknet\dump.rs
- Discuss DumpLoader and Queue once @taco-paco will come back from vacations https://github.com/0xSpaceShard/starknet-devnet-rs/pull/159#discussion_r1329906177 https://github.com/0xSpaceShard/starknet-devnet-rs/pull/159#discussion_r1329917932

**Comment by mikiw** [comment]
although it's possible to add async/await in this code, after talking with @marioiordanov I decided to drop this improvement since we have more important things to do.

interesting link:
https://greptime.com/blogs/2023-03-09-bridging-async-and-sync-rust#:~:text=Combining%20asynchronous%20code%20with%20synchronous,will%20block%20the%20current%20thread

**Comment by mikiw** [comment]
@marioiordanov @FabijanC @ivpavici I wanna close this issue. I don't think that this dumper entity or queues are needed here, also async/await is not trivial and it would require a lot of time.

**Comment by FabijanC** [comment]
Closing to prevent further notifications related to this issue. If somebody ever finds this and wants to deal with it, feel free to reopen.
