### ISSUE TITLE
Use cairo-lang-starknet for handling transaction execution errors

### ISSUE THREAD

**Issue by marioiordanov** [0xSpaceShard/starknet-devnet-rs#198]
https://github.com/0xSpaceShard/starknet-devnet-rs/blob/2e2e8e82cef8f81cc1af5fbbaa7154602796e747/crates/starknet-devnet-types/src/error.rs#L22C1-L24C51

**Comment by lordshashank** [comment]
I would like to work on this one, @ivpavici @marioiordanov , could you explain this a little more, from what I understand you want the errors [here](https://github.com/starkware-libs/cairo/blob/de1d5b1a47864a67ac8e2432323944bccae5464c/crates/cairo-lang-starknet-classes/src/casm_contract_class.rs#L64) to be integrated for contract class error handing.
Please explain more on the issue and let me know if I am going wrong.

**Comment by marioiordanov** [comment]
@lordshashank where there is an instance of `SierraCompilationError` the error from cairo_lang_starknet have to be as an inner property of `SierraCompilationError` variant, just as https://github.com/0xSpaceShard/starknet-devnet-rs/blob/2e2e8e82cef8f81cc1af5fbbaa7154602796e747/crates/starknet-devnet-types/src/error.rs#L19

**Comment by lordshashank** [comment]
@marioiordanov cairo lang starknet have multiple compilation errors [here](https://github.com/starkware-libs/cairo/blob/de1d5b1a47864a67ac8e2432323944bccae5464c/crates/cairo-lang-starknet-classes/src/casm_contract_class.rs#L64) (if I am looking at right place), do I have to match the [reason](https://github.com/0xSpaceShard/starknet-devnet-rs/blob/main/crates/starknet-devnet-types/src/error.rs#L25C30-L25C36) with the errors of cairo lang starknet to return the appropriate error?

**Comment by marioiordanov** [comment]
@lordshashank no you just have to return the error variant like in the example above

**Comment by lordshashank** [comment]
@marioiordanov is [this](https://github.com/lordshashank/starknet-devnet-rs/blob/ee86824c90e0f071dba4ea356563fd7097e5a633/crates/starknet-devnet-types/src/error.rs#L28) what you meant (I took sierra errors from cairo_lang_starknet_classes, as cairo_lang_starknet had just abi errors in it) ? I have also not removed the "reason" property, let me know if you want it removed.
