### ISSUE TITLE
Block hash computation

### ISSUE THREAD

**Issue by marioiordanov** [0xSpaceShard/starknet-devnet-rs#21]
Check the implementation of Madara project for computing the block hash.

**Comment by ivpavici** [comment]
Our hash calculation is different than on testnet / Madara.
It is probably not relevant for users, but can be improved potentially to be the same

**Comment by princeibs** [comment]
Hi @ivpavici, what is the call to action here please? I would like to hop on it.

**Comment by princeibs** [comment]
Hi @ivpavici, still anticipating your reply. Thanks

**Comment by RajeshRk18** [comment]
Can I work on this?

**Comment by princeibs** [comment]
And also going through the development docs linked in the README, I found this warning
<img width="792" alt="image" src="https://github.com/0xSpaceShard/starknet-devnet-rs/assets/64266194/3967ad6d-c1f3-447a-9a6c-1d751b527dc5">
Is it still safe to use it?
@marioiordanov @ivpavici

**Comment by princeibs** [comment]
@marioiordanov this is the closes I could find to compute block hash in Madara project: https://github.com/keep-starknet-strange/madara/blob/main/crates/primitives/block/src/header.rs#L85

Please kindly confirm if that is what I am supposed to look into?

**Comment by marioiordanov** [comment]
yes

**Comment by princeibs** [comment]
> And also going through the development docs linked in the README, I found this warning <img alt="image" width="792" src="https://private-user-images.githubusercontent.com/64266194/325262019-3967ad6d-c1f3-447a-9a6c-1d751b527dc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNDY5NDIsIm5iZiI6MTcxNDE0NjY0MiwicGF0aCI6Ii82NDI2NjE5NC8zMjUyNjIwMTktMzk2N2FkNmQtYzFmMy00NDdhLTlhNmMtMWQ3NTFiNTI3ZGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDE1NTA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YjQzYmMxMGU1OGZlMDkyNWNiODI1YmY2NzA2MDZmY2Y4Y2Q5YjBkMWQwZDg5MDA3NWMzOTc1OWJmNzUxNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DJ5YULjeZLRiAfgU7NKfREXPbOZGDTGbz3q3hwyEYvI"> Is it still safe to use it? @marioiordanov @ivpavici

@marioiordanov @ivpavici kindly see this please. It's a blocker for me.

**Comment by ivpavici** [comment]
> > And also going through the development docs linked in the README, I found this warning <img alt="image" width="792" src="https://private-user-images.githubusercontent.com/64266194/325262019-3967ad6d-c1f3-447a-9a6c-1d751b527dc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNDY5NDIsIm5iZiI6MTcxNDE0NjY0MiwicGF0aCI6Ii82NDI2NjE5NC8zMjUyNjIwMTktMzk2N2FkNmQtYzFmMy00NDdhLTlhNmMtMWQ3NTFiNTI3ZGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDE1NTA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YjQzYmMxMGU1OGZlMDkyNWNiODI1YmY2NzA2MDZmY2Y4Y2Q5YjBkMWQwZDg5MDA3NWMzOTc1OWJmNzUxNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DJ5YULjeZLRiAfgU7NKfREXPbOZGDTGbz3q3hwyEYvI"> Is it still safe to use it? @marioiordanov @ivpavici
> 
> @marioiordanov @ivpavici kindly see this please. It's a blocker for me.

Not sure what you mean about the warning? Why is it a blocker? It is a message from the old devnet, not devnet-rs

**Comment by marioiordanov** [comment]
Probably this issue is not of a such importance, because:
-  devnet doesn't have the hashes of the events, which are needed for producing the correct block hash. 
- users using devnet dont compare the block hash to the hash generated on testnet/mainnet
