### ISSUE TITLE
Trace transactions support via JSON-RPC

### ISSUE THREAD

**Issue by ivpavici** [0xSpaceShard/starknet-devnet-rs#24]
- [x] #262
- [x] #163
- [x] #270

**Comment by sgc-code** [comment]
Hi, I just want to add that `starknet_traceTransaction` would be very valuable for us. We are currently using extensively in our current tooling that's using the old python devnet (with the sequencer). And this is the last thing that we need to migrate to the new devnet.
Thanks!

**Comment by mikiw** [comment]
@sgc-code there is PR with that, currently in review, cheers!
