### ISSUE TITLE
JSON-RPC methods returning extra properties not in the spec

### ISSUE THREAD

**Issue by marioiordanov** [0xSpaceShard/starknet-devnet-rs#248]
The following methods slightly diverge from the spec, due to returning more fields than those fields in the JSON-RPC specification.
"starknet_getBlockWithTxs", "starknet_getTransactionByBlockIdAndIndex", "starknet_getTransactionByHash", "starknet_getTransactionReceipt"

**Comment by DelevoXDG** [comment]
Hi, I think this should be a part of 0.5.0 tag, it might be confusing that the tagged version is not fully compatible with the spec 😅

**Comment by marioiordanov** [comment]
starknet_getTransactionReceipt will be fixed in #273

**Comment by DelevoXDG** [comment]
@marioiordanov 

Any updates on this?

**Comment by marioiordanov** [comment]
Hey @DelevoXDG unfortunately we didn't do any work on this issue, recently. Couple of refactoring PRs took place, so we will reevaluate it.
