### ISSUE TITLE
`starknet_getTransactionByHash` returns declare transaction with `contract_class` 

### ISSUE THREAD

**Issue by DelevoXDG** [0xSpaceShard/starknet-devnet-rs#249]
**Describe the bug (observed vs expected behavior)**

`starknet_getTransactionByHash` returns declare transaction with `contract_class`. It should not ever return that in RPC 0.4.0 for get methods, and is `contract_class` is only a field in broadcasted declare txn, not a regular one.

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Run devnet-rs
2. Send a declare transaction
3. Get a receipt for declare transaction

**Devnet version**

- I am using Devnet version:
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version: 8c4b73361cb1e15412c68f18ef18da08586a8461

**System specifications**

- OS: macOS aarch64

**Comment by FabijanC** [comment]
I think this is already reported in https://github.com/0xSpaceShard/starknet-devnet-rs/issues/248

**Comment by DelevoXDG** [comment]
Sorry, didn't figure it out from the title

**Comment by FabijanC** [comment]
> Sorry, didn't figure it out from the title

I renamed it to make it clearer
