### ISSUE TITLE
starknet_traceTransaction

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#262]
Requested in https://github.com/0xSpaceShard/starknet-devnet-rs/issues/24#issuecomment-1825819672

**Comment by mikiw** [comment]
for now, I'm implementing 0.5.1 spec https://github.com/starkware-libs/starknet-specs/blob/v0.5.1/api/starknet_trace_api_openrpc.json

**Comment by mikiw** [comment]
old devnet tests to check https://github.com/0xSpaceShard/starknet-devnet/blob/master/test/test_transaction_trace.py
