### ISSUE TITLE
V3 transactions integration tests

### ISSUE THREAD

**Issue by marioiordanov** [0xSpaceShard/starknet-devnet-rs#275]
Add integration tests to v3 transactions. The reason for not being implemented is that most of the integration testing is done via starknet-rs. Now starknet-rs doesn't support v3 txns

**Comment by FabijanC** [comment]
To quote Jonathan Lei regarding the update of starknet-rs to RPC 0.6.0:
> It's being worked on (tracks `rc5`):
> https://github.com/xJonathanLEI/starknet-rs/tree/dev/jsonrpc_0_6_0
> The core model type update is done. Now just have to update the providers and use v3 across the lib

**Comment by FabijanC** [comment]
Jonathan's [update](https://t.me/starknet_rs/5070):
```
0.6.0 on `master` now. HIgher-level types (e.g. `Account`) don't make use of v3 txs yet, but I guess you're more interested in using it for RPC? Then 0.6.0 is fully supported now
```
