### ISSUE TITLE
Duplicate artifacts

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#282]
Recently duplicate artifacts have been introduced in #277 and #234, with one instance used in production, the other in testing. Including, but not limited to:
- contracts/artifacts/L1L2Example.json
- crates/starknet/contracts/artifacts/MockStarknetMessaging.json

Ideally we would be using only one instance per artifact. Perhaps we could utilize symlinks?

Related: #37

**Comment by ivpavici** [comment]
related #37

**Comment by 0xprinc** [comment]
Hey, can I work on this issue?
