### ISSUE TITLE
Missing panic reason when transaction fails during account validation

### ISSUE THREAD

**Issue by sgc-code** [0xSpaceShard/starknet-devnet-rs#286]
**Describe the bug (observed vs expected behavior)**
Looks like a regression, we have multiple tests that try to assert the panic reason thrown by the account during the `__validate__` method.
- It used to work ok in the python version
- with commit `78527decb3f76c4c808fa35f46228557af3df385` we noticed the issue in a couple of places
- with commit `85495efb71a37ad3921c8986474b7e78a9a9f5fc` we are now seeing the problem everywhere, making it impossible to run test that assert the panic reasons

**To Reproduce**
Send a transaction that will fail in the `__validate__` method of the account. The panic reason is not present in the response

**Devnet version**

- I am using Devnet version: commit 85495efb71a37ad3921c8986474b7e78a9a9f5fc, didn't happen on commit 78527decb3f76c4c808fa35f46228557af3df385
- [X] This happens with a dockerized Devnet (check the box if true).

**System specifications**

- OS: MacOS

**Comment by FabijanC** [comment]
Thanks for reporting. Can you configure your project to use the fix branch? If so, let me know how branch `fix-hidden-validation-error` works for you. I attempted a quick fix with #287, it might be improved tomorrow and merged.

**Comment by sgc-code** [comment]
> Thanks for reporting. Can you configure your project to use a fix branch? If so, let me know how branch `fix-hidden-validation-error` works for you. I attempted a quick fix with #287, it might be improved tomorrow and merged.

Thanks @FabijanC looks like its fixing the issue at least is all the scenarios i found so far. I couldn't run the whole test suite yet (for some reason it takes much longer to run, not sure if it's because i'm not using docker now). Thanks so much for the quick fix!

**Comment by FabijanC** [comment]
Thanks for trying it out. The slowdown has been reported as present since #273 was merged, we're trying to figure it out. For now I can say it's most likely not related to #272 because `starknet.js` testing workflow takes the same amount of time with and without the old state cloning (mentioned in another place as the biggest culprit for the big memory footprint).
