### ISSUE TITLE
Getting `-32602: missing field simulation_flags` in docker container

### ISSUE THREAD

**Issue by rjnrohit** [0xSpaceShard/starknet-devnet-rs#291]
2023-12-14T18:51:45.390843Z ERROR rpc: failed to deserialize method method="starknet_estimateFee" err="missing field `simulation_flags`"

**Comment by ivpavici** [comment]
hello! 
In RPC v0.6 simulation_flags is now required... Did you add it? You can just add something like this in params:
"simulation_flags": [],

**Comment by rjnrohit** [comment]
<img width="1440" alt="Screenshot 2023-12-15 at 1 21 59 PM" src="https://github.com/0xSpaceShard/starknet-devnet-rs/assets/47271616/679aab6e-d4df-4231-8043-d439000cfd62">
I didn't get any error when I tried to deploy through local instance after cloning the repo and running `cargo run` command. But I did get this error when I used docker container

**Comment by FabijanC** [comment]
Please provide here:
- the tag of your Docker image
- the git commit hash you used locally (i.e. output of `git rev-parse HEAD`)

**Comment by rjnrohit** [comment]
> Please provide here:
> 
> * the tag of your Docker image
> * the git commit hash you used locally (i.e. output of `git rev-parse HEAD`)
Okay I have updated the local repo with the `main` branch , Now I'm getting the same error on both the instances.

But here I'm trying to declare/deploy a contract through `starknet-js` lib function call which doesn't have any parameters known as `simulation_flags`

```js
const declareResponse = await account.declare({
            contract: selectedContract.sierra,
            classHash: selectedContract.classHash,
            compiledClassHash: selectedContract.compiledClassHash
          })
```

**Comment by FabijanC** [comment]
Since RPC version 0.6.0, fee estimation requires providing `simulationFlags`. The Devnet version you are using is using this new spec, but your starknet.js version isn't. To fix this, you can do one of the following:

1. Since `declare` is implicitly estimating the fee, you can explicitly provide `maxFee`:
    ```typescript
    account.declare({
            contract: selectedContract.sierra,
            classHash: selectedContract.classHash,
            compiledClassHash: selectedContract.compiledClassHash
    }, { maFee: 1e18 })
    ```
2. Alternatively: install the starknet.js `beta` version, I think that one should have 0.6.0 support (0.6.0-beta.7 is the latest beta).

**Comment by ivpavici** [comment]
btw please don't delete the issue template when reporting issues :)
