### ISSUE TITLE
Add memory performance tests

### ISSUE THREAD

**Issue by mikiw** [0xSpaceShard/starknet-devnet-rs#292]
It would be nice to have script or memory performance tests to detect memory leaks.

Maybe something similar to `crates/starknet-server/tests/test_memory_test.rs` in https://github.com/0xSpaceShard/starknet-devnet-rs/pull/276

**Comment by mikiw** [comment]
Related to https://github.com/0xSpaceShard/starknet-devnet-rs/issues/272

**Comment by FabijanC** [comment]
@hhamud What is your vision of tackling this? What exactly would you to resolve it?

**Comment by FabijanC** [comment]
Not sure that's what the issue creator had in mind; can you elaborate @mikiw ?

**Comment by ivpavici** [comment]
@hhamud good luck! 
For the beginning - you can profile the memory and find any potential leaks! Please also check devnet with state archive capacity set to full, there for sure we observe some issues:
https://github.com/0xSpaceShard/starknet-devnet-rs?tab=readme-ov-file#querying-old-state-by-specifying-block-hash-or-number

**Comment by mikiw** [comment]
I had it mind 2 ways of doing that:
1. Add test for 10000 invoke transactions (for example minting) and run it with state-archive-capacity full, and measure memory and tweak some numbers like we expect Xgb or ram to be taken and later fix memory performance problem so the test can pass (TDD approach)
2. [Easier] Add test for 10000 invoke transactions (for example minting) and test this with 2 modes --state-archive-capacity full and none. For now we expect that with none test will pass and with none it will not so for now we can add ignore like this '#[ignore = "Requires fix of performance problem in --state-archive-capacity full mode"]'
