### ISSUE TITLE
Create transactions support via JSON-RPC

### ISSUE THREAD

**Issue by ivpavici** [0xSpaceShard/starknet-devnet-rs#3]
- [x] #63
- [x] starknet_addDeclareTransaction
  - [x] `add_declare_transaction_v1`
  - [x] https://github.com/0xSpaceShard/starknet-devnet-rs/issues/79
- [x] #44

**Comment by marioiordanov** [comment]
starknet_addDeployAccountTransaction is started by me

**Comment by ivpavici** [comment]
ok, created an issue
