### ISSUE TITLE
Requests with specified block hash or number fail

### ISSUE THREAD

**Issue by DelevoXDG** [0xSpaceShard/starknet-devnet-rs#301]
**Describe the bug (observed vs expected behavior)**

Starting the recent update, some requests fail if block hash or block number is specified.
Example with `starknet_getNonce`: 
```json
{"jsonrpc":"2.0","method":"starknet_getNonce","id":0,"params":{"contract_address":"0x4428a52af4b56b60eafba3bfe8d45f06b3ba6567db259e1f815f818632fd18f","block_id":"pending"}}
{"jsonrpc":"2.0","id":0,"result":"0x14"}
```
```json
{"jsonrpc":"2.0","method":"starknet_blockHashAndNumber","id":0,"params":[]}
{"jsonrpc":"2.0","id":0,"result":{"block_hash":"0x375d2a657dd8f3c33b93b8962048f89becddf1f38d076a25543bd52e08e4140","block_number":35}}
{"jsonrpc":"2.0","method":"starknet_getNonce","id":0,"params":{"contract_address":"0x4428a52af4b56b60eafba3bfe8d45f06b3ba6567db259e1f815f818632fd18f","block_id":{"block_hash":"0x375d2a657dd8f3c33b93b8962048f89becddf1f38d076a25543bd52e08e4140"}}}
{"jsonrpc":"2.0","id":0,"error":{"code":20,"message":"Contract not found"}}
```
```json
{"jsonrpc":"2.0","method":"starknet_blockNumber","id":0,"params":[]}
{"jsonrpc":"2.0","id":0,"result":36}
{"jsonrpc":"2.0","method":"starknet_getNonce","id":0,"params":{"contract_address":"0x4428a52af4b56b60eafba3bfe8d45f06b3ba6567db259e1f815f818632fd18f","block_id":{"block_number":36}}}
{"jsonrpc":"2.0","id":0,"error":{"code":20,"message":"Contract not found"}}
```

The errors also occur upon calling:
1. `starknet_call` (different error message):
```json
{"jsonrpc":"2.0","id":0,"error":{"code":40,"message":"Contract error","data":{"revert_error":"No state at block 8"}}}
```
2. `starknet_getClassAt`
3. `starknet_getClassHashAt`

Maybe there are other cases that I don't know about.

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Get block hash/number via `starknet_blockHashAndNumber` or `starknet_blockNumber`
2. Send requests as in examples

**Devnet version**

- I am using Devnet version: 30507394204715b199989fc3d7a40c80a29e6cb0
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version: 85495efb71a37ad3921c8986474b7e78a9a9f5fc

**System specifications**

- OS: macOS aarch64

**Comment by mikiw** [comment]
This might be related to https://github.com/0xSpaceShard/starknet-devnet-rs/pull/290 but let me take a look

**Comment by mikiw** [comment]
To prevent memory exhaustion we decided to introduce a state-archive feature. From now on calling data at specific block_id requires `--state-archive-capacity full`.

I tested that locally and seems that with `--state-archive-capacity full` it's working fine. Can you confirm that @DelevoXDG?

**Comment by DelevoXDG** [comment]
Thanks, that seems to work! 

My additional suggestions are:
1. Since this a error message we're not expecting to receive by any actual node, update error message to include: `"State history is disabled; ensure running with --state-archive-capacity full"` whenever sending a request with block number or hash that is not latest.
2. In README, detail all functionalities impacted by this flag.
