### ISSUE TITLE
Create a block on demand

### ISSUE THREAD

**Issue by mikiw** [0xSpaceShard/starknet-devnet-rs#312]

**Comment by ivpavici** [comment]
Reintroducing since talking to users showed the benefits of this feature 

More info from other projects:
- https://hardhat.org/hardhat-network/docs/explanation/mining-modes#mining-modes
- https://book.getfoundry.sh/reference/anvil/#mining-modes

**Comment by FabijanC** [comment]
Simply we could re-implement what we had in Devnet-py: https://0xspaceshard.github.io/starknet-devnet/docs/guide/blocks#create-a-block-on-demand

**Comment by mikiw** [comment]
related old devnet PRs:
- https://github.com/0xSpaceShard/starknet-devnet/pull/389
- https://github.com/0xSpaceShard/starknet-devnet/pull/404
