### ISSUE TITLE
Failed to find artifacts in starknet_artifacts.json file,Please ensure you have enabled sierra and casm code generation in Scarb.toml

### ISSUE THREAD

**Issue by zouyuxuan** [0xSpaceShard/starknet-devnet-rs#319]
I use devnet to deploy the contract and an error message appears: Please ensure you have enabled sierra and casm code generation in Scarb.toml, but I have already set it in the Scarb.toml file.
[[target.starknet-contract]]
casm = true
sierra = true

scarb version is 2.4.3
cairo: 2.4.3
starkli:0.1.20

**Comment by FabijanC** [comment]
I don't think the error is coming from Devnet since Devnet doesn't rely on Scarb. Perhaps you need to recompile? Please provide more info (e.g. show the exact command you are running, show exactly how the error looks).

**Comment by zouyuxuan** [comment]
I use the “sncast --profile account3 declare --contract-name my_contract” command to declare the contractscarb 2.4.3
cairo: 2.4.3
sierra: 1.4.0
snforge 0.14.0
sncast 0.14.0
The error is the same as the title

**Comment by zouyuxuan** [comment]
I have not successfully declared it on devnet

**Comment by FabijanC** [comment]
I would advise you ask in https://github.com/foundry-rs/starknet-foundry/issues

**Comment by zouyuxuan** [comment]
all right，Thank you for your answer
