### ISSUE TITLE
test the impact of "lite" mode on devnet performance and potentially introduce it

### ISSUE THREAD

**Issue by ivpavici** [0xSpaceShard/starknet-devnet-rs#343]
More info from devnet-py docs:

https://0xspaceshard.github.io/starknet-devnet/docs/guide/lite-mode

This could potentially speed up the devnet for users who do not need block hashes

**Comment by g4titan** [comment]
hello @ivpavici , assign this task to me

**Comment by ivpavici** [comment]
@g4titan there you go! good luck!

**Comment by ivpavici** [comment]
@g4titan hi! Any progress?

**Comment by g4titan** [comment]
hey @ivpavici i couldn't fix it

**Comment by lordshashank** [comment]
@ivpavici  would like to work on this.
