### ISSUE TITLE
Transaction with query version executes successfully Instead of throwing error

### ISSUE THREAD

**Issue by ddoktorski** [0xSpaceShard/starknet-devnet-rs#349]
**Describe the bug (observed vs expected behavior)**

Currently, the devnet allows the execution of a transaction that is meant to be used for fee estimation instead of throwing an error.

**Not reproducible on alpha-goerli**

- [X] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Create any `Invoke`/`Declare`/`DeployAccount` transaction.
2. Sign the transaction off-chain for fee estimation. Use the query version (`version` + `2**128`), for example `0x100000000000000000000000000000001`.
3. Proceed to execute the transaction as if it's a normal transaction.
4. At this point, the process should produce an error. However, it successfully completes the execution instead.

**Devnet version**

- I am using Devnet version: [ebd9f85](https://github.com/0xSpaceShard/starknet-devnet-rs/tree/ebd9f8549302f91a9071fbecf69e31142554ac14)

**System specifications**

- OS: MacOS M1

**Comment by marioiordanov** [comment]
Hey @ddoktorski did you send the transaction to endpoint add_<declare/invoke/deploy_account>_transaction ?

**Comment by marioiordanov** [comment]
Only_query value of a transaction, must be based on transaction version. Not hardcoded in endpoints. Whether an error should be returned or not TBD

**Comment by ddoktorski** [comment]
Hi @marioiordanov 

> did you send the transaction to endpoint add_<declare/invoke/deploy_account>_transaction ?

If you're referring to method names that exclude underscores, such as `addInvokeTransaction`, then yes that's correct. If you meant something else, please let me know.
