### ISSUE TITLE
Devnet needs to do the compilation from Sierra to Casm

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#38]
Also includes verification.

Reported here: https://github.com/lambdaclass/starknet_in_rust/issues/791

TODO in code: https://github.com/0xSpaceShard/starknet-devnet-rs/pull/27/commits/b06a6a97a4ee00e6e93bbf8584a4bb0736d2f03d

**Comment by ivpavici** [comment]
We are compiling, but not comparing received casm and calculated hashes - so this can be improved in the future (through a new issue)
