### ISSUE TITLE
Inconsistent with starknet-spec responses

### ISSUE THREAD

**Issue by tkumor3** [0xSpaceShard/starknet-devnet-rs#381]
**Describe the bug (observed vs expected behavior)**

getBlockWithTxHashes and getStateUpdate for pending blocks return a response that is inconsistent with starknet-spec.

getBlockWithTxHashes returns extra: 'block_number', 'block_hash', 'new_root', 'status'

getStateUpdate returns extra: 'new_root', 'block_hash'

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

Call getBlockWithTxHashes and getStateUpdate for pending blocks.

**Devnet version**

- I am using Devnet version: 37dc6e6 and c6ffb99

**Comment by marioiordanov** [comment]
Hey @tkumor3 in starknet-devnet-rs every transaction is being added to a block. Requesting data from starknet-devnet-rs with block_id - pending or latest, produces the same results.

**Comment by marioiordanov** [comment]
#312 will fix this issue

**Comment by mikiw** [comment]
https://github.com/0xSpaceShard/starknet-devnet-rs/pull/430 PR will fix block_id - pending/latest logic but inconsistencies with spec will be handled as separate PR
