### ISSUE TITLE
Account deploy fee estimate

### ISSUE THREAD

**Issue by penovicp** [0xSpaceShard/starknet-devnet-rs#385]
**Describe the bug (observed vs expected behavior)**

With the starknet.js PR [#985](https://github.com/starknet-io/starknet.js/pull/985) we noticed a behaviour that might indicate an issue with devnet. After the transition from 804b361 to c6ffb99, that is, after the devnet PR #364 a test from the mentioned starknet.js PR fails. This can be seen in the following GitHub CI test runs:
- [workflow run](https://github.com/starknet-io/starknet.js/actions/runs/8328078400), branch `ETHsignerContract_1` using  804b361
- [workflow run](https://github.com/starknet-io/starknet.js/actions/runs/8328080011), branch `ETHsignerContract_2` using  c6ffb99

What happens is that the `maxFee` parameter of an account deployment, which is set automatically in the code based on the `starknet_estimateFee` response by increasing it by 50%, is still insufficient. Note that it only arises for the `ETH account tx V2` test suite.

**Not reproducible on alpha-goerli**

- [x] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**
Steps to reproduce the behaviour:

1. Fork `starknet.js`
2. Create branches based on `ETHsignerContract_1` and `ETHsignerContract_2`
3. Go to the `Actions` tab and run `[Manual] Test Devnet`

_(or equivalent steps in a local environment)_

**Devnet version**

- I am using Devnet version: c6ffb99
- [x] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version: 804b361

**System specifications**

- OS: GitHub CI runner - Ubuntu 22.04.4

**Comment by marioiordanov** [comment]
with https://github.com/0xSpaceShard/starknet-devnet-rs/pull/364 there is a change in resource weights and there is a difference between estimating fee with validation and without. So just increasing by 50% is not enough to cover the validation execution

**Comment by marioiordanov** [comment]
Closing as resolved
