### ISSUE TITLE
Set gas price

### ISSUE THREAD

**Issue by marioiordanov** [0xSpaceShard/starknet-devnet-rs#387]
Its not possible to set the price in WEI and FRI for gas_price and data_gas_price.
At this stage the gas_price value is set for eth_l1_gas_price and strk_l1_gas_price.

Introduce new cli parameters specifying the Wei_gas_price, strk_gas_price, Wei_data_gas_price, strk_data_gas_price.
Then use those new parameters in init_block_context

**Comment by Hueber9500** [comment]
hey can I work on this issue
