### ISSUE TITLE
`Contract not found` error when forking

### ISSUE THREAD

**Issue by ivpavici** [0xSpaceShard/starknet-devnet-rs#413]
**Describe the bug (observed vs expected behavior)**

```
LibraryError: RPC: starknet_getClassAt with params {
  "block_id": "pending",
  "contract_address": "0x40803f756f48576117f0b5b1d93b17c8b9787973d0d7635ff53ebb4999ecc56"
}
        20: Contract not found: undefined
```

devnet: 

**Not reproducible on testnet**

- [x] This issue is only present on Devnet and cannot be reproduced on the alpha-sepolia testnet (check the box if true).

**To Reproduce**

devnet: `3c907a6f84afe9c92119b5fac72c0182faf6711c`

command:
`cargo run --release -- --seed 0 --fork-network https://free-rpc.nethermind.io/sepolia-juno/v0_7 --chain-id TESTNET`

code in starknet.js (latest develop branch):
`provider.getClassAt('0x40803f756f48576117f0b5b1d93b17c8b9787973d0d7635ff53ebb4999ecc56')`

**Devnet version**

- I am using Devnet version: 3c907a6f84afe9c92119b5fac72c0182faf6711c
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS:

**Comment by FabijanC** [comment]
I can't find this git revision: `3c907a6f84afe9c92119b5fac72c0182faf6711c`

**Comment by FabijanC** [comment]
Never mind, it's also replicable on the currently latest commit (`9e7bc59dd47bba4015f403295d77cab53475a005`)
