### ISSUE TITLE
account_balance format

### ISSUE THREAD

**Issue by qperrot** [0xSpaceShard/starknet-devnet-rs#429]
**Describe the bug (observed vs expected behavior)**

When calling  `/account_balance?address=` it returns me an array of 3 int (ex: array[34, 7834, 984]).
It should be `low` and `high` like for cairo, but it turns out the array returned by /account_balance consists of 32-bit parts of the number.

**Not reproducible on testnet**

- [ ] This issue is only present on Devnet and cannot be reproduced on the alpha-sepolia testnet (check the box if true).

**Devnet version**

- I am using Devnet version: latest
- [x] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**Comment by FabijanC** [comment]
@marioiordanov perhaps we should have made `amount` have type `String`. It was discussed here: https://github.com/0xSpaceShard/starknet-devnet-rs/pull/394#discussion_r1538928072. Unfortunately the tests I wrote only loaded the `amount` using` BigUint` deserialization. And on creating the response the value is serialized from `BigUint` directly, so the fact that it gets converted to an array of u32 values was never discovered.
