### ISSUE TITLE
Processing pending results

### ISSUE THREAD

**Issue by taco-paco** [0xSpaceShard/starknet-devnet-rs#43]
https://github.com/0xSpaceShard/starknet-devnet-rs/blob/337b24fbab448db993c93239bba762d13d97208c/crates/server/src/rpc_handler.rs#L93-L95

shalln't it be? First await then process

```rust
Request::Batch(calls) => responses_as_batch(
    future::join_all(calls.into_iter().map(move |call| handle_call(call, handler.clone())))
        .await,
),
```

**Comment by ivpavici** [comment]
@taco-paco hi!
can you check this is it still relevant, do you maybe want to fix it or try it out?

**Comment by ivpavici** [comment]
Closing as stale
