### ISSUE TITLE
Cairo 0 artifact assertion is failing

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#434]
Currently the newly added tests from PR #380 are failing (see PR description for more info and links).

Your task, should you choose to accept it, is to find out why the tests are failing, and do one of the following:
1. Write an explanatory report as a comment on this issue.
2. Create a PR with an explanation in the description. The PR should target the branch `expand-get-class-test` (used by #380)

**Comment by kfastov** [comment]
Hello! I want to investigate this one. Can you please assign it to me?

**Comment by FabijanC** [comment]
@kfastov Hey, any update on this?
