### ISSUE TITLE
use cargo semver checks instead of the bash script

### ISSUE THREAD

**Issue by hhamud** [0xSpaceShard/starknet-devnet-rs#442]
Replace the bash script used to check for semver violations with the cargo crate.

https://github.com/obi1kenobi/cargo-semver-checks

**Comment by FabijanC** [comment]
You mean this as an alternative to which scripts exactly?

**Comment by marioiordanov** [comment]
@hhamud do you have in mind this `publish_cratesio_new_versions.sh` ?

**Comment by FabijanC** [comment]
Hey @hhamud, if you don't reply, we might close this as unclear.
