### ISSUE TITLE
Update dependencies to newest version

### ISSUE THREAD

**Issue by marioiordanov** [0xSpaceShard/starknet-devnet-rs#451]
Dependencies like: axum, hyper, tokio use old versions, but are important for the project.

**Comment by FabijanC** [comment]
Is this related to Dependabot alerts? https://github.com/0xSpaceShard/starknet-devnet-rs/security/dependabot

**Comment by marioiordanov** [comment]
no

**Comment by marioiordanov** [comment]
yes

**Comment by marioiordanov** [comment]
#426 have to be solved via the PR of this issue
