### ISSUE TITLE
Add mining blocks at a certain interval

### ISSUE THREAD

**Issue by ivpavici** [0xSpaceShard/starknet-devnet-rs#467]
A new block should be created at a fixed time interval selected by the user.

This functionality exists in Anvil and Katana:

- `evm_setIntervalMining` in https://book.getfoundry.sh/reference/anvil/#special-methods
- https://book.dojoengine.org/toolchain/katana/mining#interval-mining

**Comment by mikiw** [comment]
I can take it since it's related to time and blocks

**Comment by FabijanC** [comment]
in CLI it could be governed by:
```
--block-generation <ON_DEMAND|PERIODIC>
--block-generation-period # only usable with --block-generation PERIODIC
```

**Comment by mikiw** [comment]
requires a merge of https://github.com/0xSpaceShard/starknet-devnet-rs/pull/480/files but I already started based on this branch

**Comment by mikiw** [comment]
I'll implement `--block-generation <on_transaction|on_demand|<SECONDS>` as discussed on the chat.
