### ISSUE TITLE
Feature request: Add CLI option that loads devnet config from JSON file.

### ISSUE THREAD

**Issue by 3alpha** [0xSpaceShard/starknet-devnet-rs#475]
Passing complicated configuration settings using CLI flags can become impractical, and since there is already `/config`endpoint that dumps configuration into JSON, it only would only make sense to have CLI flag that can read file of that format to spin up devnet instance with same configuration.

**Comment by FabijanC** [comment]
If we support specifying CLI params via env vars, as proposed in #482, this issue might not require a lot (or any) work. The user could simply `source` the env file (file with env vars), or specify the path to the env file, perhaps via a dedicated env var.

E.g. assuming the user has an env file at `./env_vars`:
```bash
ACCOUNTS=3
SEED=42
```

One of the following could be implemented:

## Using `source`

Relying on `source` wouldn't require doing any work to close this issue.

```bash
source ./env_vars && starknet-devnet
```

Alternatively, run in a subshell to prevent keeping the env vars set:

```bash
( source env_vars.sh && starknet-devnet )
```

## Using an env var

Using a `DEVNET_ENV` env var would be simpler for the user, but would require adding some code logic.

```bash
DEVNET_ENV=./env_vars starknet-devnet
```
