### ISSUE TITLE
Usage examples can be added to the website

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#478]
Currently we only have `Docs` at https://0xspaceshard.github.io/starknet-devnet-rs, but we also need an `Examples` tab where various use cases will be explained step-by-step.

List of examples to be included (feel free to suggest more):
- L1-L2 communication (we could reuse the existing .md files for this)

**Comment by stevencartavia** [comment]
Hi, can I take this?

**Comment by FabijanC** [comment]
For now no - but feel free to suggest which examples should be included.

**Comment by FabijanC** [comment]
Closed via #579
