### ISSUE TITLE
Configure CLI arguments from environment variables

### ISSUE THREAD

**Issue by fracek** [0xSpaceShard/starknet-devnet-rs#482]
I'm using `starknet-devnet-rs` to test Starknet React V3 and we're hitting an issue with pending blocks and accounts (related to #474). The `--blocks-on-demand` flag helps with the issue.

We're running devnet as a service in our github actions, but github actions doesn't allow passing additional arguments to the container. I propose to make all cli arguments configurable through environment variables so that they can be used in ci.

**Comment by FabijanC** [comment]
I'm assigning myself. Seems like it could be as simple as
- expanding the clap features in Cargo.toml with `env`
- using `#[arg(env = VAR_NAME)]` on each CLI param in cli.rs.
