### ISSUE TITLE
State update multiplicity

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#485]
We have 2 files called `state_update.rs` and in `state.rs` we have several structs related to state update, including one called `StateUpdate`.

Does it have to be like that?

**Comment by khayss** [comment]
Hello, first-time contributor here.
I’m a Rust developer who loves structure and clean architecture.

I feel the current implementation is not cool. We can abstract common logic into a single file and remove unnecessary code or file.

To address the state update multiplicity, I will:

1. Analyze the two `state_update.rs` files and the `StateUpdate` struct in `state.rs` to determine their roles and relationships.
2. Decide if merging, renaming, or restructuring the files and structs is necessary for clarity and maintainability.
3. Implement the changes based on my analysis, ensuring that any refactoring does not break existing functionality.
4. Run tests to confirm that the updated structure works as intended.

**Comment by FabijanC** [comment]
Hi and thanks for reaching out! You are now assigned to this task. Please report on your progress within seven days by creating a PR (can be draft) or writing a reply to this issue.

**Comment by khayss** [comment]
Thanks for assigning the task. I will provide an update before the specified timeframe.

**Comment by khayss** [comment]
@FabijanC 
After going through the code base. The current implementation is okay. We can't merge or remove any of them without breaking the code. However, they are similar and it'll be nice if we can have a common implementation. I can work on the common implementation but will require refactoring other codes that depend on it.

Hope to get an 
update from you soon.

**Comment by FabijanC** [comment]
Try refactoring and propose your changes in a PR.

**Comment by khayss** [comment]
Alright. I'll do that.

**Comment by FabijanC** [comment]
Thanks for replying. Unassigning you.
