### ISSUE TITLE
create account with the sncast fails

### ISSUE THREAD

**Issue by gianalarcon** [0xSpaceShard/starknet-devnet-rs#487]
**Describe the bug (observed vs expected behavior)**
### Observed
Using devnet v0.0.6, input the following cli
`$ sncast   --url http://127.0.0.1:5050   account create   --name some-name`
  
  Got the following error: 
  `Provided class hash does not exist`
  
  ### Expected 
  Using devnet v0.0.5, input the same command as above, I got 
 `message: Account successfully created`

**Not reproducible on testnet**

- [x] This issue is only present on Devnet and cannot be reproduced on the alpha-sepolia testnet (check the box if true).

**To Reproduce**

1. ... Open terminal
2. ... sncast  --url http://127.0.0.1:5050  account create   --name some-name

**Devnet version**

- I am using Devnet version: 0.6.0
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version: 0.5.0

**System specifications**

- OS: Ubuntu 24.04

**Comment by marioiordanov** [comment]
It's an issue with the pending state on devnet side. With the new release this behavior is going to be fixed. Please watch out for the next release - 0.0.7

**Comment by FabijanC** [comment]
Bug fixed in #480
