### ISSUE TITLE
Why are there two BlockId implementations

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#49]
One is imported from `starknet_rs_core::types` and looks like this:
```rust
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BlockId {
    Hash(FieldElement),
    Number(u64),
    Tag(BlockTag),
}
```

the other is defined in `starknet-server/src/api/models.mod.rs` and looks like this:
```rust
#[derive(Copy, Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(untagged)]
pub enum BlockId {
    HashOrNumber(BlockHashOrNumber),
    Tag(Tag),
}
```

This `HashOrNumber` union looks wrong. The struct in `starknet_rs_core::types` has these three cases separated (Hash, Number, Tag).

Can't we just use the imported one?

**Comment by ivpavici** [comment]
@marioiordanov after the crates PR please take a look 🙏
