### ISSUE TITLE
Add an endpoint to retrieve accounts with current balance

### ISSUE THREAD

**Issue by dsperac** [0xSpaceShard/starknet-devnet-rs#495]
Currently fetching predeployed accounts returns data with only the initial balance. 

Requirement: Extend a current endpoint (e.g. /predeployed_accounts?with_balance=true) or create a new endpoint that would return the accounts with current balance included.

**Comment by FabijanC** [comment]
We can consider completely removing the `initial_balance` property. I can't think of a good purpose for it. If someone wants to know the predeployed account balance on Devnet startup, they can simply call `GET /account_balance` after startup. And once Devnet has been up for some time - why would anyone need the original balance?

It'd be a breaking change, though.

**Comment by dsperac** [comment]
> We can consider completely removing the `initial_balance` property. I can't think of a good purpose for it. If someone wants to know the predeployed account balance on Devnet startup, they can simply call `GET /account_balance` after startup. And once Devnet has been up for some time - why would anyone need the original balance?
> 
> It'd be a breaking change, though.

Let's add balance for now, because of time constraints due to demo, and we can potentially revisit after with another issue to remove the initial balance
