### ISSUE TITLE
fix `get_block_txs_count` endpoint error code

### ISSUE THREAD

**Issue by tonypony220** [0xSpaceShard/starknet-devnet-rs#496]
**Describe the bug (observed vs expected behavior)**
https://github.com/starkware-libs/starknet-specs/blob/304b952121dafe47c013ed2c4c39bef4cf4c2823/api/starknet_api_openrpc.json#L559
should return BLOCK_NOT_FOUND, but returns NO_BLOCKS

https://github.com/0xSpaceShard/starknet-devnet-rs/blob/3ad81456092a2da939be1f590855cea2c18ce40c/crates/starknet-devnet-server/src/api/json_rpc/endpoints.rs#L261

**Comment by FabijanC** [comment]
Thanks for reporting! Is this a blocker for you?
