### ISSUE TITLE
`starknet_getEvents` returning wildcard error on nonexistent block

### ISSUE THREAD

**Issue by tonypony220** [0xSpaceShard/starknet-devnet-rs#498]
**Describe the bug (observed vs expected behavior)**
version 0.0.7 with flag `--state-archive-capacity full`
when passing not existing block number got an [WILDCARD_RPC_ERROR_CODE](https://github.com/0xSpaceShard/starknet-devnet-rs/blob/3ad81456092a2da939be1f590855cea2c18ce40c/crates/starknet-devnet-server/src/api/json_rpc/mod.rs#L56) .
```
POST /rpc HTTP/1.1
user-agent: Dart/3.4 (dart:io)
content-type: application/json; charset=utf-8
accept-encoding: gzip
content-length: 149
host: 0.0.0.0:5050

{"jsonrpc": "2.0", "method": "starknet_getEvents", "params": [{"from_block": {"block_number": 100}, "to_block": "latest", "chunk_size": 0}], "id": 0}HTTP/1.1 200 OK
content-type: application/json
content-length: 71
vary: origin, access-control-request-method, access-control-request-headers
access-control-allow-origin: *
date: Mon, 17 Jun 2024 14:56:50 GMT

{"jsonrpc":"2.0","id":0,"error":{"code":-1,"message":"No block found"}}
```

should return [BLOCK_NOT_FOUND](https://github.com/starkware-libs/starknet-specs/blob/8016dd08ed7cd220168db16f24c8a6827ab88317/api/starknet_api_openrpc.json#L633)

**Comment by FabijanC** [comment]
Thanks for reporting with links!

Do you want to provide a fix PR? If not, somebody from the team will take over.

**Comment by tonypony220** [comment]
@FabijanC Of course, if there's no rush.
