### ISSUE TITLE
Error message on too big request could be more informative

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#505]
This is printed if the declaration request body is too big:
```
error WARN rpc: invalid request err=BytesRejection(FailedToBufferBody(LengthLimitError(LengthLimitError(Error { inner: LengthLimitError })))) when I try to declare my contract in localhost. with sncast. And sncast throws error error: Unknown RPC error: data did not match any variant of untagged enum JsonRpcResponse: data did not match any variant of untagged enum JsonRpcResponse
```
Originally reported on Discord ([original post](https://discord.com/channels/793094838509764618/985824027950055434/1252975759405088892)). The issue was resolved promptly.

Ideally we would tell users to use `--request-body-size-limit` without them reporting an issue.
The user reported getting this with `sncast`; perhaps that client is just not properly parsing our response, but maybe the warning log could be improved in that case.

**Comment by marioiordanov** [comment]
Unfortunately to give suggestion to the user what to do we have to implement a middleware that copies `DefaultBodyLimit` implementation from axum library
