### ISSUE TITLE
Starknet fork problems

### ISSUE THREAD

**Issue by PhilippeR26** [0xSpaceShard/starknet-devnet-rs#510]
**Describe the bug (observed vs expected behavior)**
1. Fork with a node with `https:` address is failing :
```
LibraryError: RPC: starknet_getNonce with params {
  "contract_address": "0x304c822792da45bf6f8e6957aa9515bd7b365f05b5c1678f61ae0c46213251c",
  "block_id": "pending"
}
        -1: Failed to read from state: Error in communication with origin: error sending request for url (https://free-rpc.nethermind.io/sepolia-juno/v0_7).: undefined
```

2. When Forked with a local node, it works, but the console is flooded of anxiety-provoking messages :
```
2024-06-22T16:46:37.038904Z  INFO starknet_devnet_core::starknet::defaulter: Origin response contains no 'result': {"jsonrpc":"2.0","error":{"code":20,"message":"Contract not found"},"id":0}
```

**Not reproducible on testnet**

- [x] This issue is only present on Devnet and cannot be reproduced on the alpha-sepolia testnet (check the box if true).
(by design)

**To Reproduce**
Any action that needs to interact with the real network.

**Devnet version**

- I am using Devnet version: 0.7.0 (executed from source)
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS: Linux

**Comment by mikiw** [comment]
what is 0x304c822792da45bf6f8e6957aa9515bd7b365f05b5c1678f61ae0c46213251c address? Is it predeployed account address with some seed?

**Comment by PhilippeR26** [comment]
It's an account deployed in Sepolia.

**Comment by mikiw** [comment]
right I could reproduce it thanks

**Comment by mikiw** [comment]
Hi @PhilippeR26 what endpoint are you using?

**Comment by PhilippeR26** [comment]
https://free-rpc.nethermind.io/sepolia-juno/v0_7

**Comment by mikiw** [comment]
<img width="846" alt="image" src="https://github.com/0xSpaceShard/starknet-devnet-rs/assets/5063930/fab7d8ca-817b-4818-9299-28f300322f31">

We think it is not a problem on the devnet side but on the endpoint side, I tried it from postman and got the same results.

**Comment by PhilippeR26** [comment]
So, you should add in the documentation a table with the compatible rpc nodes.

**Comment by PhilippeR26** [comment]
I would like to test different nodes and script, to try to have a better understanding of the situation.
I keep you informed here.

**Comment by PhilippeR26** [comment]
I tested with v0.1.2.
This time, with a node url starting with `https:`, it works :
```bash
cargo run --release -- --seed 0 --fork-network https://free-rpc.nethermind.io/sepolia-juno/v0_7  --state-archive-capacity full 
```

With a local node, with address starting with `http:`, it's still worling.
```bash
cargo run --release -- --seed 0 --fork-network http://192.168.1.11:9545/rpc/v0_7  --state-archive-capacity full 
`
