### ISSUE TITLE
Restrictive flags needed for running Devnet in an untrusted environment

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#511]
When Devnet is used e.g. as-a-service or in CTF competitions, it would be good to prevent it from being loadable or restartable via endpoints (if somebody thinks of other misuses, please mention them in this issue). Instead of having one flag to turn off each of these individual functionalities, I would introduce one that blocks them all, e.g.:

```
$ starknet-devnet --as-a-service
```

This flag would also incorporate the `--disable-account-impersonation` flag (perhaps one is enough?)

**Comment by marioiordanov** [comment]
I suggest the flag to be `--disable-devnet-endpoints` or `--restrictive`

**Comment by marioiordanov** [comment]
minting have to be forbidden

**Comment by FabijanC** [comment]
> I suggest the flag to be `--disable-devnet-endpoints` or `--restrictive`

Makes sense. Once we migrate to having only JSON-RPC API, implementing this would be as simple as blocking `devnet_` methods. Unless there are some that would be useful (`devnet_getConfig`? `devnet_getAccountBalance`?)

**Comment by marioiordanov** [comment]
Or maybe a cli argument that can accept a string of comma separated methods. It will override the default ones.
