### ISSUE TITLE
Optional json_rpc_handler and http_api_handler

### ISSUE THREAD

**Issue by taco-paco** [0xSpaceShard/starknet-devnet-rs#52]
https://github.com/0xSpaceShard/starknet-devnet-rs/blob/337b24fbab448db993c93239bba762d13d97208c/crates/server/src/builder.rs#L30-L31

@FabijanC @marioiordanov  can this parameters be optional? In devnet-py I see that they are always initialised. I would just propose to pass the to constructor `::new`

**Comment by FabijanC** [comment]
I don't see why they should be optional.
