### ISSUE TITLE
Builder doesn't mutate

### ISSUE THREAD

**Issue by taco-paco** [0xSpaceShard/starknet-devnet-rs#53]
https://github.com/0xSpaceShard/starknet-devnet-rs/blob/337b24fbab448db993c93239bba762d13d97208c/crates/server/src/builder.rs#L71

Right now every time any function on builder is called callee loses ownership of `Builder` object because it's moved. In my opinion every function except of `build` is setter function & configures object. I would propose using `&mut self` instead and `fn build` will consume the object which is also a question if it shall do that on `build`, I'm not sure

**Comment by ivpavici** [comment]
@taco-paco hi again!
can you check this is it still relevant, do you maybe want to fix it or try it out?

**Comment by ivpavici** [comment]
Closing as stale
