### ISSUE TITLE
dev: detect chain id on fork

### ISSUE THREAD

**Issue by EvolveArt** [0xSpaceShard/starknet-devnet-rs#535]
**Describe the bug (observed vs expected behavior)**

The chain id should be detected automatically when using a fork network otherwise it can lead to unexpected behavior.

**Not reproducible on testnet**

- [x] This issue is only present on Devnet and cannot be reproduced on the alpha-sepolia testnet (check the box if true).

**To Reproduce**

1. Run `starknet-devnet --fork-network https://starknet-mainnet.public.blastapi.io/rpc/v0_7 --host 127.0.0.1 --port 56126 --accounts 1 --seed 1` for example
2. Chain ID is not detected automatically

**Devnet version**

- I am using Devnet version: 0.0.7
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS: Mac M1

**Comment by FabijanC** [comment]
Thanks for reporting. Currently we only log a warning. In case of a solution that would automatically detect the origin chain ID, we should remove the warning.
