### ISSUE TITLE
Invalid predeployed ERC20 data

### ISSUE THREAD

**Issue by tonypony220** [0xSpaceShard/starknet-devnet-rs#544]
**Wrong function used**
 https://github.com/0xSpaceShard/starknet-devnet-rs/blob/38aa51eb9951597a22acbeab4a64e33181dbaf7e/crates/starknet-devnet-core/src/starknet/predeployed.rs#L36
it should be not selector but to-cario-stirng or something.

**Comment by FabijanC** [comment]
If you haven't already prepared a PR, I'll check it out. Thanks for reporting.

**Comment by tonypony220** [comment]
```
starkli storage 0x49D36570D4E46F48E99674BD3FCC84644DDD6B96F7C741B1562B82F9E004DC7 ERC20_symbol --rpc https://starknet-mainnet.g.alchemy.com/v2/XXXXXXXXXXXXXXXXXXXXXXXX
0x0000000000000000000000000000000000000000000000000000000000455448
```
```
starkli storage 0x49D36570D4E46F48E99674BD3FCC84644DDD6B96F7C741B1562B82F9E004DC7 ERC20_symbol --

0x02aebeba3810b1e6b70781f14b2d72c1cb89c0b2b320c43bb67ff79f562f5ff4
```

**Comment by FabijanC** [comment]
Ah ok, now I see what you mean; the value assigned to the key is wrong, not the key itself.

**Comment by FabijanC** [comment]
Feel free to review: https://github.com/0xSpaceShard/starknet-devnet-rs/pull/546
