### ISSUE TITLE
Periodic block generation tests are flaky

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#550]
As witnessed here: https://app.circleci.com/pipelines/github/0xSpaceShard/starknet-devnet-rs/2281/workflows/162119c5-a0de-411c-9dbc-698486da8b3d/jobs/3439

## Problem

The problem is in the fact that in `--block-generation-on <INTERVAL>`, a new block is generated right after the genesis block. This is done on a separate thread, and in the workflow linked above, it lagged a bit, so the first of the five executed transactions was included in this first periodic block, while the remaining for were included in the expected second periodic block.

## Solution

We could try things that involve longer generation periods and additional sleeps. But what seems like the best solution is to stop this initial block generation.

**Comment by mikiw** [comment]
wasn't this fixed in this PR https://github.com/0xSpaceShard/starknet-devnet-rs/pull/541/commits/5ea8085143e890669c3ab4ea6b54c0868699b92a

**Comment by mikiw** [comment]
TODO: rethink genesis block + instant first periodic block, maybe use `delay_for` from tokio library
