### ISSUE TITLE
Support asdf Installation: Create asdf plugin

### ISSUE THREAD

**Issue by gianalarcon** [0xSpaceShard/starknet-devnet-rs#584]
**Describe the bug (observed vs expected behavior)**

Currently, switching between versions requires using `cargo install starknet-devnet --version x.x.x`. It would be beneficial to integrate with [asdf](https://asdf-vm.com/guide/getting-started.html) for version management.

Here are examples of other projects that support asdf:
- scarb: https://github.com/software-mansion/asdf-scarb 
- dojo: https://book.dojoengine.org/getting-started#install-dojo-using-asdf
- snfoundry: https://foundry-rs.github.io/starknet-foundry/getting-started/installation.html#installation-via-asdf

For reference, see how Dojo integrates asdf:  
https://github.com/dojoengine/asdf-dojo/pull/2

**Comment by ptisserand** [comment]
Hi, if needed here is a link to my asdf plugin repository: https://github.com/ptisserand/asdf-starknet-devnet

**Comment by ivpavici** [comment]
Thanks @ptisserand ! I tried it out and looks nice!
We can mention your repo to our docs!

**Comment by ptisserand** [comment]
@ivpavici I will ask for [integration in asdf-community](https://github.com/asdf-community/.github/blob/master/GUIDELINES.md), which github username should add in maintainers list ?

**Comment by ivpavici** [comment]
Thanks!
You can add:
- https://github.com/FabijanC
- https://github.com/marioiordanov

**Comment by ptisserand** [comment]
Asdf community infrastructure PR: https://github.com/asdf-community/infrastructure/pull/205
