### ISSUE TITLE
Fork support in 0.04 version

### ISSUE THREAD

**Issue by BlackStarkGoku** [0xSpaceShard/starknet-devnet-rs#585]
When running 0.0.4 version image, forking does not work.
![image](https://github.com/user-attachments/assets/6fde83bd-2a4d-4a93-9421-40bf36d83513)

1. Run : docker pull shardlabs/starknet-devnet-rs:0.0.4-seed0
2. Run : docker run -p 5050:5050 shardlabs/starknet-devnet-rs:0.0.4-seed0 --fork-network [https://rpc.nethermind.io/mainnet-juno\?apikey\=](https://rpc.nethermind.io/mainnet-juno/?apikey\=) 

- I am using Devnet version: 0.04
- [v] This happens with a dockerized Devnet (check the box if true).
- OS: Macos

**Comment by ivpavici** [comment]
hello!
We had a bug https://github.com/0xSpaceShard/starknet-devnet-rs/issues/424 ... which was fixed in later versions!
Please update to a newer version!
