### ISSUE TITLE
Use Result with default Error type

### ISSUE THREAD

**Issue by FabijanC** [0xSpaceShard/starknet-devnet-rs#68]
Currently we rely on the type `DevnetResult`, but this PR #65 is introducing the `Result` type with a default Error type:
```rust
pub type Result<T, E = Error> = std::result::Result<T, E>;
```

We should use that in the rest of the code.

But maybe we also ought to preserve the name `DevnetResult` to avoid confusion of our custom `Result` and `std::result::Result`

**Comment by marioiordanov** [comment]
closed in https://github.com/0xSpaceShard/starknet-devnet-rs/pull/137
